---
apiVersion: v1
kind: Secret
metadata:
  name: n8n-secrets
type: Opaque
data:
  username: bm8x # "no1" en base64, cambia esto
  password: c3VwZXJzZWNyZXQ= # "supersecret" en base64, cámbialo
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: n8n-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: n8n-service
spec:
  type: NodePort
  selector:
    app: n8n
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5678
      nodePort: 30078
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: n8n
  labels:
    app: n8n
spec:
  replicas: 1
  selector:
    matchLabels:
      app: n8n
  template:
    metadata:
      labels:
        app: n8n
    spec:
      containers:
        - name: n8n
          image: n8nio/n8n:latest
          ports:
            - containerPort: 5678
          env:
            - name: N8N_BASIC_AUTH_ACTIVE
              value: "true"
            - name: N8N_BASIC_AUTH_USER
              valueFrom:
                secretKeyRef:
                  name: n8n-secrets
                  key: username
            - name: N8N_BASIC_AUTH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: n8n-secrets
                  key: password
            - name: WEBHOOK_URL
              value: "http://n8n-service" # Puedes cambiarlo a tu dominio público
            - name: N8N_HOST
              value: "0.0.0.0"
            - name: N8N_PORT
              value: "5678"
            - name: N8N_PROTOCOL
              value: "http"
            - name: N8N_DIAGNOSTICS_ENABLED
              value: "false"
            - name: N8N_SECURE_COOKIE
              value: "false"
          volumeMounts:
            - name: n8n-data
              mountPath: /home/node/.n8n
      volumes:
        - name: n8n-data
          persistentVolumeClaim:
            claimName: n8n-pvc
