---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: obsidian-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: obsidian-service
spec:
  type: NodePort
  selector:
    app: obsidian
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30087
    - protocol: TCP
      port: 3001
      targetPort: 3001
      nodePort: 30088
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: obsidian
  labels:
    app: obsidian
spec:
  replicas: 1
  selector:
    matchLabels:
      app: obsidian
  template:
    metadata:
      labels:
        app: obsidian
    spec:
      securityContext:
        seccompProfile:
          type: Unconfined # seccomp:unconfined en Kubernetes moderno
      containers:
        - name: obsidian
          image: lscr.io/linuxserver/obsidian:latest
          ports:
            - containerPort: 3000
            - containerPort: 3001
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "Europe/Madrid"
          volumeMounts:
            - name: obsidian-data
              mountPath: /config
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
        # Aquí se podría mapear /dev/dri si quieres
      volumes:
        - name: obsidian-data
          persistentVolumeClaim:
            claimName: obsidian-pvc
      # shm_size no existe como tal en spec, se puede mapear si montamos emptyDir (te puedo explicar si quieres)
