apiVersion: apps/v1
kind: Deployment
metadata:
  name: pihole
  labels:
    app: pihole
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pihole
  template:
    metadata:
      labels:
        app: pihole
    spec:
      dnsPolicy: ClusterFirstWithHostNet
      nodeSelector:
        kubernetes.io/hostname: usrv
      containers:
        - name: pihole
          image: pihole/pihole:latest
          imagePullPolicy: Always
          env:
            - name: TZ
              value: Europe/Madrid
            - name: WEBPASSWORD
              value: "password"
            - name: DNS1
              value: 1.1.1.1
            - name: DNS2
              value: 8.8.8.8
            - name: FTLCONF_LOCAL_IPV4
              value: <IP_DEL_NODO_USRV>  # Reemplaza esto manualmente
          ports:
            - containerPort: 53
              hostPort: 53
              protocol: TCP
            - containerPort: 53
              hostPort: 53
              protocol: UDP
            - containerPort: 67
              hostPort: 67
              protocol: UDP
            - containerPort: 80
              hostPort: 90
              protocol: TCP
          securityContext:
            capabilities:
              add: ["NET_ADMIN"]
          volumeMounts:
            - name: etc-pihole
              mountPath: /etc/pihole
            - name: etc-dnsmasq
              mountPath: /etc/dnsmasq.d
      volumes:
        - name: etc-pihole
          hostPath:
            path: /home/docker/pihole/etc-pihole
            type: DirectoryOrCreate
        - name: etc-dnsmasq
          hostPath:
            path: /home/docker/pihole/etc-dnsmasq.d
            type: DirectoryOrCreate
